server:
  port: 8050

microservices:
  urls:
    archive: ${ARCHIVE_URL:http://localhost:8089}
    files: ${FILES_URL:http://localhost:8088}
    tech: ${TECH_URL:http://localhost:8087}

logs:
  detail:
    enabled: ${LOGS_DETAIL_ENABLED:true}

spring:
  cloud:
    gateway:
      routes:
        - id: units
          uri: ${microservices.urls.archive}
          predicates:
            - Method=POST,PATCH,PUT,GET
            - Path=/api/v1/units,/api/v1/units/{number}
        - id: files
          uri: ${microservices.urls.files}
          predicates:
            - Method=POST,GET
            - Path=/api/v1/drawings/{number}
        - id: tech
          uri: ${microservices.urls.tech}
          predicates:
            - Method=POST,GET
            - Path=/api/v1/equipments,/api/v1/equipments/{number}
