basicEnabled: true
basic:
  replicaCount: 1
  
  image:
    repository: "ghcr.io/yuryklimchuk"
    tag: "prodms/gateway-server"
    version: "1.0.0-SNAPSHOT"
    pullPolicy: Always
  
  app:
    id: "gateway"
    port: 8080

microservices:
  urls:
    archive: ${ARCHIVE_URL:http://localhost:8089}
    files: ${FILES_URL:http://localhost:8088}
