basicEnabled: true
basic:
  replicaCount: 1
  
  image:
    repository: "ghcr.io/yuryklimchuk"
    tag: "prodms/gateway-server"
    version: "1.0.0-SNAPSHOT"
    pullPolicy: Always
  
  app:
    id: "gateway"
    port: 8080

microservices:
  urls:
    archive: http://archive-svc.prodms.svc:8080
    files: http://files-svc.prodms.svc:8080
    auth: http://auth-svc.prodms.svc:8000

